# Generated by Django 3.2.2 on 2021-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modeForm',
            new_name='modelForm',
        ),
    ]
